### ISSUE TITLE
Examples of adding meta properties to update a profile

### ISSUE THREAD

**Issue by parachute-dev** [zac-schutt/KlaviyoSharp#20]
Apologies! I cant' seem to work out the format expected for adding custom fields for profiles - does anyone have a working example? 

nevermind - there are unit tests! will use those.

**Comment by TIMGATVOLER** [comment]
@parachute-dev  did you ever figure out a working example of this.  I don't see any examples in the unit tests related to adding or updating custom fields for profiles.
